import { Fragment, useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { Search, Plus, Pencil, Trash2, ChevronRight, ChevronLeft, Baby, AlertTriangle, X } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "../lib/trpc";
import { useAuth } from "../_core/hooks/useAuth";
import ConfirmDialog from "./ConfirmDialog";

type ChildRow = {
  id: number;
  childId: string;
  ageMonths: number;
  sex: string;
  weightKg: string;
  heightCm: string;
  muacCm: string | null;
  createdAt: string;
  updatedAt: string;
};

const PAGE_SIZE = 8;

function EmptyState({ onAdd }: { onAdd: () => void }) {
  const { t } = useTranslation();
  return (
    <div className="module-state" style={{ padding: "48px 20px" }}>
      <Baby size={40} style={{ color: "#c4d2e2", margin: "0 auto 12px" }} />
      <p style={{ fontSize: "13px", fontWeight: 600, color: "#334155", marginBottom: "4px" }}>{t("data.noChildren")}</p>
      <p style={{ fontSize: "12px", color: "#718096", marginBottom: "16px" }}>
        {t("data.noChildrenDescription")}
      </p>
      <button className="primary-btn" onClick={onAdd}>
        <Plus size={14} /> {t("data.registerChild")}
      </button>
    </div>
  );
}

function ChildFormModal({
  open,
  onClose,
  onSave,
  initial,
  isPending,
  generatedId,
}: {
  open: boolean;
  onClose: () => void;
  onSave: (data: { childId: string; ageMonths: number; sex: string; weightKg: number; heightCm: number; muacCm?: number }) => void;
  initial?: ChildRow | null;
  isPending: boolean;
  generatedId?: string;
}) {
  const { t } = useTranslation();
  const isEdit = Boolean(initial);
  const [childId, setChildId] = useState(initial?.childId ?? "");
  const [ageMonths, setAgeMonths] = useState(initial?.ageMonths?.toString() ?? "");
  const [sex, setSex] = useState(initial?.sex ?? "Male");
  const [weightKg, setWeightKg] = useState(initial?.weightKg ?? "");
  const [heightCm, setHeightCm] = useState(initial?.heightCm ?? "");
  const [muacCm, setMuacCm] = useState(initial?.muacCm ?? "");

  useEffect(() => {
    if (open && !isEdit && generatedId) {
      setChildId(generatedId);
    }
  }, [open, isEdit, generatedId]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const age = parseInt(ageMonths, 10);
    const weight = parseFloat(weightKg);
    const height = parseFloat(heightCm);
    const muac = muacCm ? parseFloat(muacCm) : undefined;
    if (!childId.trim() || isNaN(age) || isNaN(weight) || isNaN(height)) {
      toast.error(t("data.fillRequired"));
      return;
    }
    onSave({
      childId: childId.trim(),
      ageMonths: age,
      sex,
      weightKg: weight,
      heightCm: height,
      muacCm: muac,
    });
  };

  if (!open) return null;

  return (
    <div className="modal-backdrop" role="presentation" onMouseDown={(e) => e.target === e.currentTarget && onClose()}>
      <div className="modal-card" role="dialog" aria-modal="true">
        <button className="dialog-close" onClick={onClose}><X size={17} /></button>
        <h3>{isEdit ? t("data.editChild") : t("data.registerNewChild")}</h3>
        <p>{isEdit ? t("data.editDescription") : t("data.registerDescription")}</p>
        <form onSubmit={handleSubmit}>
          <label>
            {t("data.childId")}
            <input
              value={childId}
              onChange={(e) => setChildId(e.target.value)}
              placeholder={isEdit ? "" : t("data.generating")}
              disabled
              required
            />
            {!isEdit && generatedId && (
              <span style={{ fontSize: "11px", color: "#64748b", marginTop: "4px", display: "block" }}>
                {t("data.autoGenerated")}
              </span>
            )}
          </label>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "0 14px" }}>
            <label>
              {t("data.ageMonths")}
              <input
                type="number"
                min={0}
                max={60}
                value={ageMonths}
                onChange={(e) => setAgeMonths(e.target.value)}
                placeholder="0–60"
                required
              />
            </label>
            <label>
              {t("data.sex")}
              <select value={sex} onChange={(e) => setSex(e.target.value)}>
                <option value="Male">{t("options.male")}</option>
                <option value="Female">{t("options.female")}</option>
              </select>
            </label>
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "0 14px" }}>
            <label>
              {t("data.weight")}
              <input
                type="number"
                step="0.1"
                min={0}
                value={weightKg}
                onChange={(e) => setWeightKg(e.target.value)}
                placeholder="e.g. 8.4"
                required
              />
            </label>
            <label>
              {t("data.height")}
              <input
                type="number"
                step="0.1"
                min={0}
                value={heightCm}
                onChange={(e) => setHeightCm(e.target.value)}
                placeholder="e.g. 78.0"
                required
              />
            </label>
          </div>
          <label>
            MUAC (cm) — {t("data.optional")}
            <input
              type="number"
              step="0.1"
              min={0}
              value={muacCm}
              onChange={(e) => setMuacCm(e.target.value)}
              placeholder="e.g. 11.2"
            />
          </label>
          <div style={{ display: "flex", justifyContent: "flex-end", gap: "9px", marginTop: "18px" }}>
            <button type="button" className="outline-btn" onClick={onClose}>{t("data.cancel")}</button>
            <button type="submit" className="primary-btn" disabled={isPending}>
              {isPending ? t("data.saving") : isEdit ? t("data.updateChild") : t("data.registerChild")}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

export default function DataManagement() {
  const { t } = useTranslation();
  const { user } = useAuth();
  const isAdmin = user?.role === "admin";
  const [query, setQuery] = useState("");
  const [page, setPage] = useState(0);
  const [formOpen, setFormOpen] = useState(false);
  const [editingChild, setEditingChild] = useState<ChildRow | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<ChildRow | null>(null);
  const [expandedChild, setExpandedChild] = useState<number | null>(null);
  const [generatedChildId, setGeneratedChildId] = useState("");

  const utils = trpc.useUtils();

  const childrenQuery = trpc.data.children.useQuery();
  const maternalQuery = trpc.data.maternal.useQuery();
  const householdQuery = trpc.data.household.useQuery();
  const healthQuery = trpc.data.healthEnvironment.useQuery();
  const generateIdQuery = trpc.prediction.generateId.useQuery(undefined, { enabled: false });

  const createMutation = trpc.data.createChild.useMutation({
    onSuccess: () => {
      toast.success(t("data.created"));
      utils.data.children.invalidate();
      setFormOpen(false);
    },
    onError: (err) => toast.error(err.message || t("data.createFailed")),
  });

  const updateMutation = trpc.data.updateChild.useMutation({
    onSuccess: () => {
      toast.success(t("data.updated"));
      utils.data.children.invalidate();
      setFormOpen(false);
      setEditingChild(null);
    },
    onError: (err) => toast.error(err.message || t("data.updateFailed")),
  });

  const deleteMutation = trpc.data.deleteChild.useMutation({
    onSuccess: () => {
      toast.success(t("data.deleted"));
      utils.data.children.invalidate();
      setDeleteTarget(null);
    },
    onError: (err) => toast.error(err.message || t("data.deleteFailed")),
  });

  const children: ChildRow[] = useMemo(() => {
    if (!childrenQuery.data) return [];
    return (childrenQuery.data as any[]).map((c: any) => ({
      id: c.id,
      childId: c.childId,
      ageMonths: c.ageMonths,
      sex: c.sex,
      weightKg: String(c.weightKg ?? ""),
      heightCm: String(c.heightCm ?? ""),
      muacCm: c.muacCm != null ? String(c.muacCm) : null,
      createdAt: c.createdAt,
      updatedAt: c.updatedAt,
    }));
  }, [childrenQuery.data]);

  const filtered = useMemo(() => {
    if (!query.trim()) return children;
    const q = query.toLowerCase();
    return children.filter((c) =>
      c.childId.toLowerCase().includes(q) ||
      c.sex.toLowerCase().includes(q) ||
      c.ageMonths.toString().includes(q)
    );
  }, [children, query]);

  const totalPages = Math.ceil(filtered.length / PAGE_SIZE);
  const paged = filtered.slice(page * PAGE_SIZE, (page + 1) * PAGE_SIZE);

  const relatedByChild = useMemo(() => {
    const map: Record<number, { maternal: any[]; household: any[]; health: any[] }> = {};
    const lists = [
      { key: "maternal" as const, data: maternalQuery.data },
      { key: "household" as const, data: householdQuery.data },
      { key: "health" as const, data: healthQuery.data },
    ];
    for (const list of lists) {
      if (!list.data) continue;
      for (const row of list.data as any[]) {
        const cid = row.childId;
        if (!map[cid]) map[cid] = { maternal: [], household: [], health: [] };
        map[cid][list.key].push(row);
      }
    }
    return map;
  }, [maternalQuery.data, householdQuery.data, healthQuery.data]);

  const handleSave = (data: { childId: string; ageMonths: number; sex: string; weightKg: number; heightCm: number; muacCm?: number }) => {
    if (editingChild) {
      updateMutation.mutate({ id: String(editingChild.childId), data });
    } else {
      createMutation.mutate(data);
    }
  };

  const handleDelete = () => {
    if (!deleteTarget) return;
    deleteMutation.mutate({ id: String(deleteTarget.childId) });
  };

  const openEdit = (child: ChildRow) => {
    setEditingChild(child);
    setFormOpen(true);
  };

  const openCreate = async () => {
    setEditingChild(null);
    setGeneratedChildId("");
    setFormOpen(true);
    const r = await generateIdQuery.refetch();
    if (r.data?.childId) {
      setGeneratedChildId(r.data.childId);
    }
  };

  const loading = childrenQuery.isLoading;
  const error = childrenQuery.isError;

  return (
    <>
      <div className="panel-heading" style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", flexWrap: "wrap", gap: "12px" }}>
        <div>
          <h2>{t("data.childrenRegistered")}</h2>
          <p style={{ fontSize: "12px", color: "#718096", margin: "2px 0 0" }}>
            {loading ? t("data.loading") : t("data.childrenInSystem", { count: children.length })}
          </p>
        </div>
        <button className="primary-btn" onClick={openCreate} style={{ display: "inline-flex", alignItems: "center", gap: "6px" }}>
          <Plus size={14} /> {t("data.registerChild")}
        </button>
      </div>

      <div className="module-controls">
        <div className="search-bar">
          <Search size={16} />
          <input
            value={query}
            onChange={(e) => { setQuery(e.target.value); setPage(0); }}
            placeholder={t("data.searchPlaceholder")}
          />
        </div>
      </div>

      {loading && (
        <div className="module-state">{t("data.loading")}</div>
      )}

      {error && (
        <div className="module-state error">{t("data.loadError")}</div>
      )}

      {!loading && !error && children.length === 0 && (
        <EmptyState onAdd={openCreate} />
      )}

      {!loading && !error && children.length > 0 && (
        <>
          <div className="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>{t("data.childId")}</th>
                  <th>{t("data.age")}</th>
                  <th>{t("data.sex")}</th>
                  <th>{t("data.weight")}</th>
                  <th>{t("data.height")}</th>
                  <th>MUAC (cm)</th>
                  <th>{t("data.registered")}</th>
                  <th style={{ textAlign: "right" }}>{t("data.actions")}</th>
                </tr>
              </thead>
              <tbody>
                {paged.map((child) => {
                  const isExpanded = expandedChild === child.id;
                  const related = relatedByChild[child.id];
                  const hasRelated = related && (related.maternal.length > 0 || related.household.length > 0 || related.health.length > 0);
                  return (
                    <Fragment key={child.id}>
                      <tr>
                        <td>
                          <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                            {hasRelated && (
                              <button
                                style={{ background: "none", border: "none", padding: "2px", color: "#718096" }}
                                onClick={() => setExpandedChild(isExpanded ? null : child.id)}
                                title={t("data.viewRelated")}
                              >
                                <ChevronRight size={14} style={{ transform: isExpanded ? "rotate(90deg)" : "none", transition: "transform .15s" }} />
                              </button>
                            )}
                            <span style={{ fontWeight: 600, fontSize: "12px" }}>{child.childId}</span>
                          </div>
                        </td>
                        <td>{child.ageMonths} mo</td>
                        <td>{child.sex}</td>
                        <td>{child.weightKg}</td>
                        <td>{child.heightCm}</td>
                        <td>{child.muacCm ?? "—"}</td>
                        <td>{child.createdAt ? new Date(child.createdAt).toLocaleDateString() : "—"}</td>
                        <td>
                          <div className="table-actions" style={{ justifyContent: "flex-end" }}>
                            <button className="table-action" onClick={() => openEdit(child)}>
                              <Pencil size={12} /> {t("data.edit")}
                            </button>
                            {isAdmin && (
                              <button className="table-action danger" onClick={() => setDeleteTarget(child)}>
                                <Trash2 size={12} /> {t("data.delete")}
                              </button>
                            )}
                          </div>
                        </td>
                      </tr>
                      {isExpanded && related && (
                        <tr key={`${child.id}-related`}>
                          <td colSpan={8} style={{ padding: "0 13px 14px", background: "#f8fafc" }}>
                            <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "12px", marginTop: "8px" }}>
                              <RelatedSection
                                title={t("data.maternalInformation")}
                                rows={related.maternal}
                                emptyText={t("data.noMaternal")}
                              />
                              <RelatedSection
                                title={t("data.householdInformation")}
                                rows={related.household}
                                emptyText={t("data.noHousehold")}
                              />
                              <RelatedSection
                                title={t("data.healthEnvironment")}
                                rows={related.health}
                                emptyText={t("data.noHealth")}
                              />
                            </div>
                          </td>
                        </tr>
                      )}
                    </Fragment>
                  );
                })}
              </tbody>
            </table>
          </div>

          {totalPages > 1 && (
            <div className="pagination">
              <button className="secondary-btn" disabled={page === 0} onClick={() => setPage((p) => p - 1)}>
                <ChevronLeft size={14} /> {t("data.previous")}
              </button>
              <span>{t("data.pageOf", { page: page + 1, total: totalPages })}</span>
              <button className="secondary-btn" disabled={page + 1 >= totalPages} onClick={() => setPage((p) => p + 1)}>
                {t("data.next")} <ChevronRight size={14} />
              </button>
            </div>
          )}
        </>
      )}

      {formOpen && (
        <ChildFormModal
          open={formOpen}
          onClose={() => { setFormOpen(false); setEditingChild(null); setGeneratedChildId(""); }}
          onSave={handleSave}
          initial={editingChild}
          isPending={createMutation.isPending || updateMutation.isPending}
          generatedId={generatedChildId}
        />
      )}

      <ConfirmDialog
        open={Boolean(deleteTarget)}
        title={t("data.deleteTitle")}
        description={t("data.deleteDescription", { id: deleteTarget?.childId })}
        confirmLabel={t("data.confirmDelete")}
        destructive
        onCancel={() => setDeleteTarget(null)}
        onConfirm={handleDelete}
      />
    </>
  );
}

function RelatedSection({ title, rows, emptyText }: { title: string; rows: any[]; emptyText: string }) {
  return (
    <div style={{ background: "#fff", border: "1px solid #e3e9f1", borderRadius: "8px", padding: "12px" }}>
      <p style={{ fontSize: "11px", fontWeight: 700, color: "#334155", margin: "0 0 8px", textTransform: "uppercase", letterSpacing: "0.04em" }}>{title}</p>
      {rows.length === 0 ? (
        <p style={{ fontSize: "11px", color: "#718096", margin: 0 }}>{emptyText}</p>
      ) : (
        rows.map((row, i) => (
          <div key={row.id ?? i} style={{ fontSize: "11px", color: "#4a5a70", padding: "6px 0", borderTop: i > 0 ? "1px solid #f1f5f9" : "none" }}>
            {row.data && typeof row.data === "object" ? (
              Object.entries(row.data).slice(0, 5).map(([k, v]) => (
                <div key={k} style={{ display: "flex", gap: "6px" }}>
                  <span style={{ color: "#718096", minWidth: "80px" }}>{k}:</span>
                  <span>{String(v ?? "—")}</span>
                </div>
              ))
            ) : (
              <span style={{ color: "#718096" }}>Record #{i + 1}</span>
            )}
          </div>
        ))
      )}
    </div>
  );
}
